version: '3'

services:
   # AdGuard Home
   adguardhome:
      image: adguard/adguardhome
      container_name: adguardhome
      ports:
         - 53:53/tcp
         - 53:53/udp
         - 80:80/tcp
         - 443:443/tcp
         - 443:443/udp
         - 3000:3000/tcp
         - 853:853/tcp
         - 784:784/udp
         - 853:853/udp
         - 8853:8853/udp
         - 5443:5443/tcp
         - 5443:5443/udp
      volumes:
         - '${CONFIG_PATH}/.docker-configs/adguardhome/work:/opt/adguardhome/work'
         - '${CONFIG_PATH}/.docker-configs/adguardhome/conf:/opt/adguardhome/conf'
      restart: unless-stopped
   # Media servers:
   qbittorrent:
      image: lscr.io/linuxserver/qbittorrent:latest
      container_name: qbittorrent
      environment:
         - 'PUID=${UID}'
         - 'PGID=${GID}'
         - 'TZ=${TIMEZONE}'
         - WEBUI_PORT=8112
      volumes:
         - '${CONFIG_PATH}/.docker-configs/qbittorrent/config:/config'
         - '${MEDIA_PATH}/@Media-server/Downloads:/downloads'
      ports:
         - 8112:8112
         - 6881:6881
         - 6881:6881/udp
      networks:
         media-server:
            ipv4_address: 169.0.0.2
      restart: unless-stopped
   #  deluge:
   #     image: lscr.io/linuxserver/deluge
   #     container_name: deluge
   #     environment:
   #        - 'PUID=${UID}'
   #        - 'PGID=${GID}'
   #        - 'TZ=${TIMEZONE}'
   #        - DELUGE_LOGLEVEL=error #optional
   #     volumes:
   #        - '${CONFIG_PATH}/.docker-configs/deluge/config:/config'
   #        - '${MEDIA_PATH}/@Media-server/Downloads:/downloads'
   #     ports:
   #        - 8112:8112
   #        - 6881:6881
   #        - 6881:6881/udp
   #     networks:
   #        media-server:
   #           ipv4_address: 169.0.0.2
   #     restart: unless-stopped
   prowlarr:
      image: lscr.io/linuxserver/prowlarr:latest
      container_name: prowlarr
      environment:
         - 'PUID=${UID}'
         - 'PGID=${GID}'
         - 'TZ=${TIMEZONE}'
      volumes:
         - '${CONFIG_PATH}/.docker-configs/prowlarr/config:/config'
         - '${MEDIA_PATH}/@Media-server/Downloads:/downloads'
      ports:
         - 9696:9696
      networks:
         media-server:
            ipv4_address: 169.0.0.3
      restart: unless-stopped
   radarr:
      image: lscr.io/linuxserver/radarr
      container_name: radarr
      environment:
         - 'PUID=${UID}'
         - 'PGID=${GID}'
         - 'TZ=${TIMEZONE}'
      volumes:
         - '${CONFIG_PATH}/.docker-configs/radarr/config:/config'
         - '${MEDIA_PATH}/@Media-server/Movies:/movies'
         - '${MEDIA_PATH}/@Media-server/Downloads:/downloads'
      ports:
         - 7878:7878
      networks:
         media-server:
            ipv4_address: 169.0.0.4
      restart: unless-stopped
   sonarr:
      image: lscr.io/linuxserver/sonarr
      container_name: sonarr
      environment:
         - 'PUID=${UID}'
         - 'PGID=${GID}'
         - 'TZ=${TIMEZONE}'
      volumes:
         - '${CONFIG_PATH}/.docker-configs/sonarr/config:/config'
         - '${MEDIA_PATH}/@Media-server/TV Shows:/tv'
         - '${MEDIA_PATH}/@Media-server/Anime:/anime'
         - '${MEDIA_PATH}/@Media-server/Downloads:/downloads'
      ports:
         - 8989:8989
      networks:
         media-server:
            ipv4_address: 169.0.0.5
      restart: unless-stopped
   bazarr:
      image: lscr.io/linuxserver/bazarr
      container_name: bazarr
      environment:
         - 'PUID=${UID}'
         - 'PGID=${GID}'
         - 'TZ=${TIMEZONE}'
      volumes:
         - '${CONFIG_PATH}/.docker-configs/bazarr/config:/config'
         - '${MEDIA_PATH}/@Media-server/TV Shows:/tv'
         - '${MEDIA_PATH}/@Media-server/Anime:/anime'
         - '${MEDIA_PATH}/@Media-server/Movies:/movies'
      ports:
         - 6767:6767
      networks:
         media-server:
            ipv4_address: 169.0.0.6
      restart: unless-stopped
networks:
   media-server:
      external: true
